name: frontend testing workflow

on:
  push:
    branches: [ frontend-testing ]
  pull_request:
    branches: [ frontend-testing ]

jobs:
  lint-test-build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: npm install and build
        run: |
          cd ./backend && npm install
          cd ..
          cd ./webapp && npm install && npm run lint
          cd ..
          cd ./backend && npm run build --if-present
          cd ..
          cd ./backend && npm start & npx wait-on http://localhost:5000
        env:
        CI: true
      - name: run frontend tests
        run: cd ./webapp && jest --coverage --forceExit
        env: 
        CI: true